### ISSUE TITLE
SyntaxError: invalid syntax on Line 237?

### ISSUE THREAD

**Issue by thereddestdog** [jonfairbanks/sonarr-episode-trimmer#4]
So I have been using the original GitLab script for years, but I think it broke when I upgraded Sonarr to v4.. No problem, I found this project. But when I execute it, I get this error:

![image](https://github.com/jonfairbanks/sonarr-episode-trimmer/assets/24947579/4f18e133-53e4-401c-9696-d2094a0aa005)

I am trying to run it on Windows, are the updates to work with Docker only or something?

**Comment by thereddestdog** [comment]
Also, how can this script be called in Sonarr v4 since Arguments have been removed?

![image](https://github.com/jonfairbanks/sonarr-episode-trimmer/assets/24947579/68de2a12-803a-41a4-b45b-4a28a3751b4a)

**Comment by thereddestdog** [comment]
Going to document my findings here....

OK so I needed to have Python3 installed. That fixed the above syntax error.

However, then I got a different error:

![MbyVkJs](https://github.com/user-attachments/assets/6220c252-0aa4-451f-9d7a-da7fd0393f17)

I then needed to install additional Python3 components: requests, and flask


```

C:\sonarr-episode-trimmer>"C:\sonarr-episode-trimmer\sonarr-episode-trimmer.py" --config config.ini --list-series
Traceback (most recent call last):
  File "C:\sonarr-episode-trimmer\sonarr-episode-trimmer.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\sonarr-episode-trimmer>cd "C:\Program Files (x86)\Python313-32"

C:\Program Files (x86)\Python313-32>cd "C:\Program Files (x86)\Python313-32\Scripts"

C:\Program Files (x86)\Python313-32\Scripts>pip3 install requests
Collecting requests
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.0-cp313-cp313-win32.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading charset_normalizer-3.4.0-cp313-cp313-win32.whl (94 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
  WARNING: The script normalizer.exe is installed in 'C:\Program Files (x86)\Python313-32\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed certifi-2024.8.30 charset-normalizer-3.4.0 idna-3.10 requests-2.32.3 urllib3-2.2.3

C:\Program Files (x86)\Python313-32\Scripts>"C:\sonarr-episode-trimmer\sonarr-episode-trimmer.py" --config config.ini --list-series
Traceback (most recent call last):
  File "C:\sonarr-episode-trimmer\sonarr-episode-trimmer.py", line 12, in <module>
    from flask import Flask, request, jsonify
ModuleNotFoundError: No module named 'flask'

C:\Program Files (x86)\Python313-32\Scripts>pip3 install flask
Collecting flask
  Downloading flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Collecting Werkzeug>=3.0.0 (from flask)
  Downloading werkzeug-3.0.6-py3-none-any.whl.metadata (3.7 kB)
Collecting Jinja2>=3.1.2 (from flask)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting itsdangerous>=2.1.2 (from flask)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting click>=8.1.3 (from flask)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting blinker>=1.6.2 (from flask)
  Downloading blinker-1.8.2-py3-none-any.whl.metadata (1.6 kB)
Collecting colorama (from click>=8.1.3->flask)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=3.1.2->flask)
  Downloading MarkupSafe-3.0.2-cp313-cp313-win32.whl.metadata (4.1 kB)
Downloading flask-3.0.3-py3-none-any.whl (101 kB)
Downloading blinker-1.8.2-py3-none-any.whl (9.5 kB)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading werkzeug-3.0.6-py3-none-any.whl (227 kB)
Downloading MarkupSafe-3.0.2-cp313-cp313-win32.whl (15 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: MarkupSafe, itsdangerous, colorama, blinker, Werkzeug, Jinja2, click, flask
  WARNING: The script flask.exe is installed in 'C:\Program Files (x86)\Python313-32\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Jinja2-3.1.4 MarkupSafe-3.0.2 Werkzeug-3.0.6 blinker-1.8.2 click-8.1.7 colorama-0.4.6 flask-3.0.3 itsdangerous-2.2.0

C:\Program Files (x86)\Python313-32\Scripts>"C:\sonarr-episode-trimmer\sonarr-episode-trimmer.py" --config config.ini --list-series
None/api/v3/series
Traceback (most recent call last):
  File "C:\sonarr-episode-trimmer\sonarr-episode-trimmer.py", line 231, in <module>
    series = api_request("series")
  File "C:\sonarr-episode-trimmer\sonarr-episode-trimmer.py", line 73, in api_request
    r = requests.request(method, url, params=params)
  File "C:\Program Files (x86)\Python313-32\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Python313-32\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Program Files (x86)\Python313-32\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
    ~~~~~~~~~^
        method=request.method.upper(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        hooks=merge_hooks(request.hooks, self.hooks),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Program Files (x86)\Python313-32\Lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Python313-32\Lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
    ...<2 lines>...
    )
requests.exceptions.MissingSchema: Invalid URL 'None/api/v3/series': No scheme supplied. Perhaps you meant https://None/api/v3/series?

```

**Comment by jonfairbanks** [comment]
Converting this to a discussion as I do not see any code-level bugs/issues called out here. This seems to be related to environment setup.
